var username = "Rabiya";
alert(username);
var myname = "Rabiya Usman Ghani";
alert(myname);
var message = "Hello World";
alert(message);
var name = "Jhone Doe";
var age = "15 years old";
var course = "Certified Mobile Application Development";
alert(name);
alert(age);
alert(course);
var pizza = "PIZZA\nPIZZ\nPIZ\nPI\nP";
alert(pizza);
var email = "rabiya.usmanghani@gmail.com";
alert("My email address is "+email);
var book = "A Smarter way to learn Java Script";
alert ("I am trying to learn from the Book "+ book );
document.write("Yah! I can write HTML content through JavaScript.<br>");
var string = "“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”";
alert(string);
document.write(string);
