var name = prompt ("Your name", "Type your name here");
var fathername = prompt("Your father name", "Type your father name here");
var age = prompt ("Your age","Type your age here");
document.write("My name is "+ name +" "+ fathername +".I am "+age + " years old.");
document.write("<br>I declared 3 variables in one statement. <br>");
document.write("<h3>Legal variables names</h3>");
var legal = "$,1,alpahabets,_, are legal variables.<br>" ;
document.write(legal);
document.write("<h3>Illegal variable names</h3>");
var illegal = "space in variable declaration, not camel case, not javascript keywords.";
document.write(illegal);
document.write("<h5>Declare five legal variables</h5>");
var names = "Bilal";
var fullname = "Ahmed";
var age = "22";
var course = "Graphic Designing";
var qualification = "Metric";
document.write(names + "<br>" + fullname + "<br>" + age + "<br>" + course + "<br>" + qualification);
document.write("<h5>Declare five illegal variables</h5>");
document.write("Illegal variables can't be declared because it give an error.");
var heading = "<h3>Rules for naming JS variables:</h3>";
var i = "Variables name can only contain letter, digits, underscore and dollar sign.";
var ii = "Variales must begins with $name._name or name.";
var iii = "Variables names are case sensitive.";
var iv = "Variables name should not be JS keywords.";
document.write(heading + "<br>" + i + "<br>" + ii+ "<br>" + iii+ "<br>" + iv);