var a = 3;
var b = 5;
var c = a+b;
document.write("<h5>Sum of "+ a + " and " + b + " is " + c + ".</h5>");
var d = b-a;
document.write("<h5>Subtraction of "+ a + " from " + b + " is " + d + ".</h5>");
var e = a*b;
document.write("<h5>Multiplication of "+ a + " and " + b + " is " + e + ".</h5>");
var f = b/a;
document.write("<h5>Division of "+ a + " and " + b + " is " + f + ".</h5>");
var g = a%b;
document.write("<h5>Modules  of "+ a + " and " + b + " is " + g + ".</h5>");
var value = "undefined";
document.write("<h5> Value after variable declaration is "+ value+" .</h5>")
var x = 5;
document.write("<h5>Initial value: "+x+".</h5>");
var x = ++x;
document.write("<h5>Value after increment is: "+x+".</h5>");
var y = x + 7;
document.write("<h5>Value after addition is: " + y +".</h5>");
var y = --y;
document.write("<h5>Value after decrement is: " + y +".</h5>");
var z = y%3;
document.write("<h5>The remainder is: " + z +".</h5>");
var movtic = 600;
var ticpri = movtic * 5;
document.write("<h5>Total cost to buy 5 tickets to a movie is " + ticpri +" PKR.</h5>");
document.write("<h3>Table of 4</h3>");
for (var i = 1; i<= 10; i++){
	document.write("<h4>4" + " X " + i +" = "+4*i + ".<br></h4>");
};
var C = 25;
var F = (C * 9/5)+32;
document.write("<h5>"+C + " &#8451 is "+ F +" &#8457.</h5>");
var f = 70;
var c = (f-32)*5/9;
document.write("<h5> "+f + " &#8457 is "+c+" &#8451.</h5>")
var pi1 = 650;
var pi2 = 100;
var q1 = 3;
var q2 = 7;
var sc = 100;
document.write("<h2>Shopping Cart</h2>");
document.write("<h5>Price of item 1 is "+ pi1 + "<br> Quantity of item 1 is "+ q1 + "<br> Price of item  2 is "+ pi2 +"<br> Quantity of item 2 is "+ q2 + "<br> Shipping Charges "+ sc + "</h5>")
var tc  = (pi1 *q1)+ (pi2 * q2)+sc;
document.write("<h4>Total cost of your order is "+ tc +".</h4>");
var tm = 980;
var om = 804;
var per = (om/tm)*100;
document.write("<h2>Marks Sheet</h2>");
document.write("<h5>Total marks : " + tm + "<br> Marks obtained :"+om+"<br> Percentage: "+per +"%</h5>");
var currency = (10 * 104.80)+(25*28);
document.write("<h2>Currency in PKR</h2>");
document.write("<h5>Total currency in PKR : "+currency+"</h5>");
var num = 20;
var num1 = ((num+5)*10)/2;
document.write("<h5>Answer no 10 is: "+num1+"</h5>");
document.write("<h2>Age Calculator</h2>");
var cy = 2020;
var by = 1998;
var yage = cy-by;
document.write("<h5> Current Year: "+cy+"<br>Birth Year: "+by+"<br>Your Age is:"+yage+"</h5>");
var pi = 3.142;
var r = 20;
var cir = 2*pi*r;
var area = (r*r)*x;
document.write("<h2>The Geometrizer</h2>");
document.write("<h5>The circumference is: "+cir+"<br>The area is: "+area+"</h5>");
document.write("<h2>The Lifetime Supply Calculator</h2>");
var favsna = "Dairy Milk";
var curage = 24;
var maxage = 90;
var perday = 5;
var total = (maxage-curage)*perday;
document.write("<h5>Favourite Snack : "+favsna+"<br>Current age: "+curage+"<br>Estimated Maximum Age:"+maxage+"<br>Amount of sancks per day: "+perday+"<br>You will need "+total+" "+favsna+" to last you until the ripe old age of "+maxage+"</h5>");